config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get  'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orderables
  has_many :carts, through: :orderables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_render_cart
  before_action :initialize_cart

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id])

    if @cart == nil
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)

    if current_orderable && quantity > 0
      current_orderable.update(quantity:)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity:)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart }), turbo_stream.replace(@product)]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart })
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show; end
  def edit; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product) }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
    end
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <h1>Cart</h1>
  
  <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
    <p>Total: <%= @cart.total %></p>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>

  <br>
  <hr>
  <br>
<% end %>

app/views/cart/_orderables.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>

  <div id="<%= "cart-#{product.id}" %>">
    <div style="display: flex;justify-content: space-between;margin: 0em 5em;">
      <strong>Name:</strong>
      <%= product.name %>

      <strong>Description:</strong>
      <%= product.description %>

      <strong>Price:</strong>
      <%= product.price %>

      <%= form_with(url: cart_add_path) do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        <%= f.number_field :quantity, value: orderable.quantity, min: 0 %>
        <%= f.submit "Add to Cart" %>
      <% end %>

      <%= form_with(url: cart_remove_path) do |f| %>
        <%= f.hidden_field :id, value: orderable.id %>
        <%= f.submit "X" %>
      <% end %>

      <strong>Total:</strong>
      <%= orderable.total %>
    </div>
  </div>
<% end %>

app/views/cart/show.html.erb
<h1>Your Cart</h1>

<%= @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
  <p><%= product.name %> * <%= orderable.quantity %> = <%= product.price * orderable.quantity %></p>
<% end %>

<p>Your total is: <%= @cart.total %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoping Cart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <main class="container my-5">
      <%= render partial: "cart/cart" if @render_cart %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>

  <% if product.errors.any? %>
    <p><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</p>
    <% product.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div style="display: flex;justify-content: space-between;margin: 0em 5em;">
    <strong>Name:</strong>
    <%= product.name %>

    <strong>Description:</strong>
    <%= product.description %>

    <strong>Price:</strong>
    <%= product.price %>

    <%= form_with(url: cart_add_path) do |f| %>
      <%= f.hidden_field :id, value: product.id %>
      <%= f.number_field :quantity, value: 0, min: 1 %>
      <%= f.submit "Add to Cart" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>